### ISSUE TITLE
Issue with OSX "brew install chromedriver"

### ISSUE THREAD

**Issue by subzerofun** [Kitryn/PTCAccount2#1]
Hey just figured out if you install chromedriver with "brew install chromedriver" brew uses the wrong one, the 32bit version! (http://chromedriver.storage.googleapis.com/2.23/chromedriver_mac32.zip)

using ptc2 with that version just gives you a lot of errors like 
`Attempting to create user neverGonnaGiveYouUp. Opening browser...
Traceback (most recent call last):
  File "/usr/local/bin/ptc2", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.1', 'console_scripts', 'ptc2')()
  File "/Users/david/github/PokemonGo/AccountCreation/PTCAccount2/ptcaccount2/console.py", line 43, in entry
    account_info = ptcaccount2.random_account(args.username, args.password, args.email)
  File "/Users/david/github/PokemonGo/AccountCreation/PTCAccount2/ptcaccount2/accounts.py", line 162, in random_account
    account_created = create_account(try_username, password, try_email)
  File "/Users/david/github/PokemonGo/AccountCreation/PTCAccount2/ptcaccount2/accounts.py", line 73, in create_account
    driver = webdriver.Chrome()`

So to get this to work for OSX users you have to install the 64bit version of chromedriver:
http://chromedriver.storage.googleapis.com/2.23/chromedriver_mac64.zip

To update the brew formula, use this:
`brew edit chromedriver`

And then change the line url from `...mac32.zip` to
`"https://chromedriver.storage.googleapis.com/2.23/chromedriver_mac64.zip"`

and sh256 goes like that:
`sha256 "47a8caec6ce251f2dbaa9005e4dc783cb1fa6c09ecd76afafa41eab540a32e86"`

now `brew uninstall chromedriver` (if you have installed the 32bit one)
and `brew install chromedriver`

now it should work! at least it does for me (OSX 10.10.5).

@Kitryn btw - thanks for the code!

**Comment by Kitryn** [comment]
Thanks for the troubleshoot! I didn't have any problems with it but I'll update the readme when I get the chance.

Also I feel like it would be easier to use a Firefox driver since that only requires having Firefox installed, but I couldn't get it to work so I used the ChromeDriver instead.
