### ISSUE TITLE
Using Temporary email services

### ISSUE THREAD

**Issue by mjmjelde** [Kitryn/PTCAccount2#13]
Is it possible to use temporary email services in this application instead of generating completely random ones?

I say this because using random emails doesn't help... you will only be able to use the account for a short period before services require you to activate your ptc account... and with a random email, you cant

**Comment by Kitryn** [comment]
See #7 for using the same gmail account for multiple registrations. This script only handles the interface with PTC, so any email handling you'll have to handle on your own. You can script it with the function this package exposes when you import it; the command line interface also allows you to specify a custom email. I'm at work right now so I can't paste an example script I've been using to create multiple accounts with email validation, maybe later
