### ISSUE TITLE
Opens PTC Window but then nothing?

### ISSUE THREAD

**Issue by cdicey** [Kitryn/PTCAccount2#14]
I'll admit, I am 100% new in using ChromeDriver, so I'm sorry if this is a stupid-easy fix.

When I run "ptc2" with or without -- commands, the PTC website opens in a new window but... that's it. None of the info is filled in, it's just the Create Account page. Here is what is in my prompt:

Susan@Susan-HP MINGW64 ~/Desktop/chromedriver_win32
$ ptc2
Creating new account:
Attempting to create user GeXMiiXGOojRF96:uSuZ5eyhZHTp5LU. Opening browser...
Step 1: Verifying age using birthday: 1959-01-15
Traceback (most recent call last):
  File "C:\Python27\Scripts\ptc2-script.py", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.2', 'console_scripts', 'ptc2')()
  File "c:\python27\lib\site-packages\ptcaccount2\console.py", line 47, in entry
    account_info = ptcaccount2.random_account(args.username, args.password, args.email, args.birthday)
  File "c:\python27\lib\site-packages\ptcaccount2\accounts.py", line 210, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday)
  File "c:\python27\lib\site-packages\ptcaccount2\accounts.py", line 125, in create_account
    elem.clear()
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 87, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element must be user-editable i                                                                                                                                                       n order to clear it.
  (Session info: chrome=51.0.2704.103)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10586 x86_6                                                                                                                                                       4)

Thanks for everything!

**Comment by Kitryn** [comment]
Hi!

`selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element must be user-editable i n order to clear it.`

That's a really weird error, since the code explicitly removes the readonly attribute before trying to clear the element. Is the error consistent on every run, or does it only happen sporadically?

**Comment by Kitryn** [comment]
May be related to #15, could you verify? Thanks!

EDIT: The latest update to the repository (fb7a857) fixed an issue relating to the datepicker, which is what your error referred to. It should fix your error if it was caused by seeing a UK/Europe version of the sign up page.

**Comment by cdicey** [comment]
Sorry for being MIA. THe update fixed it, and it's running perfectly! Thanks so much!
