### ISSUE TITLE
Different date format (by region?)

### ISSUE THREAD

**Issue by nik-humphries** [Kitryn/PTCAccount2#15]
The normal script asks for YYYY-MM-DD but my client requires DD-MM-YYYY

Here is a grab of the form - https://gyazo.com/7a10e0d44089c2956c470cef03370b5a

The 3 date elements are part of one larger element. Each is clickable and can be altered by either typing or using a set of arrows that appear onscreen. The URL is https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ which would imply a "US" site.

If you submit a DOB and then return to the first page without completing the account setup, the format becomes YYYY-MM-DD as so - https://gyazo.com/658a4143a31b9cf3ddc5d8996aaa3c76 and is greyed out requiring you to change the readonly attribute of the field.

> Does YYYY-MM-DD work when you submit it with your page, or does the website throw an error? (@Kitryn)

It is not possible to input YYYY-MM-DD without completely altering the element to a standard text box.

"US version"
`<input class="" id="id_dob" name="dob" readonly="readonly" title="yyyy-mm-dd" type="text" value="1989-08-16" data-emoji_font="true" style="font-family: Roboto, arial, sans-serif, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, Symbola, EmojiSymbols !important;">`

"UK Version"
`<input id="id_dob" name="dob" class="datepicker" type="date" value="2016-08-16">`

If you replace the UK version of the element with the US version and of course delete the readonly attribute (you can even just edit the element value) and submit the form, then it appears to work fine. No errors thrown by the website.

I suppose you could also just alter the "value" of the "UK" version as it has the same date format.

**Comment by Kitryn** [comment]
I just pushed commit fb7a857; could you help me test that to see if that works? The new commit works on YYYY-MM-DD format pages, but I can't find a way to test on the UK version. Thanks a lot!

**Comment by nik-humphries** [comment]
Works great, cheers.
