### ISSUE TITLE
[Improvement] Print username:password in a csv file

### ISSUE THREAD

**Issue by octave-ati** [Kitryn/PTCAccount2#16]
Hello,

Would that be possible easily? 
I tried to implement it myself but sadly my programming skills are not good enough

Thanks in advance

**Comment by nik-humphries** [comment]
I added this to console.py. The USERNAME:PASSWORD format is used by pogom so you can just copy and paste them in.

```
if args.compact:
    print('{}:{}'.format(account_info["username"], account_info["password"]))
    writeto = open("C:/Your/Directory/accounts.txt",'a+')
    writeto.write('{}:{}'.format(account_info["username"], account_info["password"]) + "\n")
    writeto.close()
```

If you remove the "C:/Your/Directory/" then the file will save to wherever you run ptc2 from.

Note if you do this yourself you need to rebuild and also run in compact mode (--compact).
`python setup.py build; python setup.py install`

**Comment by octave-ati** [comment]
Thank you, couldn't you commit that to the master branch?
I'm sure others will be interested

**Comment by nik-humphries** [comment]
I've only just started using github so I'm unsure if it worked but I tried
to pull a better variation of this earlier?

**Comment by sriyegna** [comment]
I believe only the owner or anyone they authorize can commit it to master. Others can fork it and make the change on their own fork.
Slightly shortened code... 
`with open('C:/PTCaccount/user.txt', 'a') as myfile:
                myfile.write('{}:{}\n'.format(account_info["username"],`

**Comment by octave-ati** [comment]
The thing is, on windows I feel like the pip install git+url sets up something in my temp folder hardly accessible. 
Now I cloned the files from the repo in a local folder but they aren't the root for my "ptc2" command so I don't think editing them will have an impact.

Will the build / install command when bashed from my local repo make it the source from my ptc2 install?

**Comment by Kitryn** [comment]
pip install installs the package "globally" in the site-packages directory, unless you're using a virtualenv, so yes editing your copy doesn't change the ptc2 command. You can run pip install git+url to overwrite the currently installed version of it.

Currently working with @Shadowfish26 to get the changes pulled into the master branch!

**Comment by octave-ati** [comment]
Perfect, I'll wait for a commit then so I will be able to install the package globally using the git+url command

**Comment by Kitryn** [comment]
Committed to master. Thanks @Shadowfish26
