### ISSUE TITLE
What is pip installation

### ISSUE THREAD

**Issue by nicolalol2** [Kitryn/PTCAccount2#18]
I am not a python programmer and i dont know what is a pip installation, can you tell me what's the " pip install " you say there in the guide ? i know that's something related to python because i googled it but can't find a proper way to install pip. i dont even know what pip is

**Comment by nik-humphries** [comment]
This isn't really an appropriate question for here, but you can find step by step instructions on how to install pip here - https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py

pip installs modules and libraries for Python for you, it is documented here - https://pip.pypa.io/en/latest/reference/. You first need to add Python onto your machine.

**Comment by nicolalol2** [comment]
i did everything, i am now stucked at 

" run ptca2" from cmd or whatever. What's the exact command i have to type there?

**Comment by nik-humphries** [comment]
You need to first do
`python setup.py --build; python setup.py --install`
(I think with dashes)

Then in the terminal type 
`ptc2`

**Comment by Kitryn** [comment]
Thanks @Shadowfish26. Closing this issue.
