### ISSUE TITLE
Please randomize Age

### ISSUE THREAD

**Issue by subzerofun** [Kitryn/PTCAccount2#2]
In accounts.py could you please add a function that randomizes the Input Age?

It will seem very suspicious to Niant*c if hundreds of users, created within a short time, all have the same age. and then someone fires up a scanner with 100 accounts, and everyone of them has the same age data. Would fix it myself - i know it´s probaby ridiculously easy, but i have no experience with python.

`    # Input age: 1992-01-08
    print("Step 1: Verifying age")
    driver.get("{}/sign-up/".format(BASE_URL))
    assert driver.current_url == "{}/sign-up/".format(BASE_URL)
    elem = driver.find_element_by_name("dob")
    driver.execute_script("arguments[0].removeAttribute('readonly')", elem)
    elem.clear()
    elem.send_keys("1992-01-08")
    elem.submit()
`

**Comment by Kitryn** [comment]
Latest commit c168975 adds this feature (:
