### ISSUE TITLE
Accounts not working on scanner

### ISSUE THREAD

**Issue by LumbaJack** [Kitryn/PTCAccount2#21]
Sorry if i missed a step i created the accounts and verified them via the gmail trick. Any idea why they would be failing via pogo scanners? Is there an implied step that I am missing after creating the accounts?

**Comment by sriyegna** [comment]
Did you complete the TOS?

**Comment by Kitryn** [comment]
See #20

**Comment by LumbaJack** [comment]
That was it thanks.
