### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print

### ISSUE THREAD

**Issue by sapphirecz** [Kitryn/PTCAccount2#26]
Hey,
after recent upgrade from 2.0.3 to 2.0.6 I'm recievening this error message:

[user@localhost ~]$ ptc2
Traceback (most recent call last):
  File "/usr/bin/ptc2", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.6', 'console_scripts', 'ptc2')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python3.4/site-packages/ptcaccount2/console.py", line 83
    print "Appended to file accounts.txt"
                                        ^
SyntaxError: Missing parentheses in call to 'print'
[user@localhost ~]$ 

sapphire

**Comment by diveflo** [comment]
#27 should fix this. Until it's merged you could just fix it yourself, by opening console.py and editing line 83. Replace
`print "Appended to file accounts.txt"`
with
`print("Appended to file accounts.txt")`

Though you might consider installing Python 2.7. Afaik most PokemonGo related stuff is implemented with 2.7, so you often run into problems like this.

**Comment by sapphirecz** [comment]
Hello, 

first of all, I'd like to thanks for such a quick response.

[user@localhost ptcaccount2]$ ptc2
Traceback (most recent call last):
  File "/usr/bin/ptc2", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.6', 'console_scripts', 'ptc2')()
  File "/usr/lib/python3.4/site-packages/ptcaccount2/console.py", line 60, in entry
    if len(args.email) > 75:
TypeError: object of type 'NoneType' has no len()
[sapphire@localhost ptcaccount2]$ sudo nano console.py 
[sapphire@localhost ptcaccount2]$ ptc2 -h
usage: ptc2 [-h] [-u USERNAME] [-p PASSWORD] [-e EMAIL] [-b BIRTHDAY]
            [-m MULTIPLE] [--compact] [--tofile] [--email-tag]
Is it correct here? https://github.com/Kitryn/PTCAccount2/commit/573195ce3d68fb46c7698b16c405b6d81782bb18
It even doesn't  work in python 2.

Is it now mandatory to specify email adress? Seems to work only with filled email option.

Thanks.

sapphire

**Comment by diveflo** [comment]
Yeah looks like the console entry has an error there. Internally it's still possible to use a random address, I'll look into it tomorrow :)
Though I would recommend using a real email address (and activate the "email tag", if you're creating multiple accounts) because the PTC accounts will be sea deaktivated after 2 days if you don't click the link.

**Comment by Kitryn** [comment]
Thanks @diveflo. Latest commit fixes it
