### ISSUE TITLE
Exception if no email specified

### ISSUE THREAD

**Issue by nik-humphries** [Kitryn/PTCAccount2#28]
Getting an error with the the latest multi account + email commit. It tries to check the length of the email in line 60 of console.py which of course raises an exception if you don't specify an email.

Solution is probably to change this line to this.

```
if len(args.email) > 75:
if args.email is not None and len(args.email) > 75:
```

I'd do this myself but my laptop is being buggy, this means I also don't know if there are any other problems if you do not specify an email .

**Comment by Kitryn** [comment]
This is what I get for committing code at 1am. Thanks!
