### ISSUE TITLE
Idea / Query - PTC2 Proxy Integration

### ISSUE THREAD

**Issue by nexusvue** [Kitryn/PTCAccount2#31]
Hey Guys, 

Been using this for a while now and i'm starting to think all Pokemon GO have to do is reference all accounts made by the same IP and blacklist those accounts. 

See it as a pre-precaution i guess, but it's starting to feel like that's happening.

**Comment by sapphirecz** [comment]
Hey,

on linux, just install tor, launch ptc2 skript with while loop in bash where you can restart tor service during a specific period (enough for new tor proxy connection)

saph

**Comment by sapphirecz** [comment]
Maybe --tor=xy parameter in sec or value of repeats might be implemented with "sudo systemctl restart tor" command for bash users who would like automatically restart the tor service in specified period? I still think that its way easier and better do it via own bash command loop skript..

**Comment by Kitryn** [comment]
Good precaution, but out of the scope of this repo; any proxying should be handled by external scripts like @sapphirecz suggested.
