### ISSUE TITLE
[Feature Request] Automated captcha service support

### ISSUE THREAD

**Issue by aldarund** [Kitryn/PTCAccount2#33]
Add possibility to solve captcha using automated services like deathbycaptcha or similar

**Comment by diveflo** [comment]
Do they work with google's recaptcha? Didnt' really find anything on their website except that they would "return the captcha text", which doesn't help with recaptcha

**Comment by aldarund** [comment]
Yes, they are. At least deathbycaptcha for sure.  Send them image and they return coordinates that should be clicked, there example when u login and download their python sdk.

**Comment by diveflo** [comment]
That sounds interesting. I'm out of town for a few days, maybe someone else can have a look. Otherwise I'll check it out next week :) Thanks for the tip!

**Comment by Kitryn** [comment]
This package is just a wrapper around PTC's account creation page, and as such shouldn't handle such tasks. This should be the responsibility of any user-created scripts using this package's exported functions. 

That being said, I can facilitate this by enabling users to specify their own CAPTCHA handlers when calling `PTCAccount2.random_account()` in their scripts. Standard behaviour would call the default handler which simply waits for the user to input the captcha, but you could make a script that specifies a different user-created handler that calls whatever service they want. How does that sound?

The interface would look something like this:

``` python
def random_account(
        username=None,
        password=None,
        email=None,
        birthday=None,
        email_tag=None,
        captcha_handler=_default_captcha_handler):
    ...
    ...
    ...
```

where `captcha_handler` takes a single argument `driver` (which would be the Selenium WebDriver), allowing the handler function to control the webpage.

**Comment by aldarund** [comment]
That sound good, but why not include other captcha handlers in repo like a plugins too, that can be enabled by some option, if someone actually write them ? :)

**Comment by Kitryn** [comment]
This is just a wrapper around PTC, which is the reason why this repo exports the random_accounts() function. Another repository can implement a fully featured auto-account-creation script that say, has 3rd party captcha solvers, has multithreading to do multiple requests, has auto-ToS accepting, etc etc. That repository can include this repository in pip's `requirements.txt` file as a dependency with a line such as `git+https://github.com/Kitryn/PTCAccount2.git#egg=PTCAccount2` and then installation will be a breeze. 

What I'm trying to say is, other programs can build on this one, but this one should keep it simple and just abstract the account creation process. If anyone needs the custom captcha handler, I can always push my local branch to github (:

**Comment by a-moss** [comment]
I implemented automated captchas with Death By Captcha. Unfortunately, I had to tear apart a bit of the original code to do this. 

@Kitryn Your suggested implementation of this would work perfectly (the captcha handler). This would allow me to use DBC without editing the original code. +1, I would love to see this feature.

**Comment by Kitryn** [comment]
@a-moss what parameters do you need to implement it? My current handler on my local repo only receives the webdriver object so far, is that enough?

``` python
def _handler(driver):
...
```

**Comment by a-moss** [comment]
@Kitryn 
Yup, the webdriver object is all that is really needed. That should work

**Comment by Kitryn** [comment]
@a-moss Change is now up in the `custom-handler` branch of the repo
