### ISSUE TITLE
Issues with ChromeDriver

### ISSUE THREAD

**Issue by shre0047** [Kitryn/PTCAccount2#34]
I am trying to run ptc2.exe but get the following errors:
`Creating new account:
Attempting to create user ZDlhlOalmSNxOks:GZEMbunGmwWqrws. Opening browser...
Traceback (most recent call last):
  File "C:\Python27\Scripts\ptc2-script.py", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.2', 'console_scripts', 'ptc2')()
  File "build\bdist.win32\egg\ptcaccount2\console.py", line 47, in entry
  File "build\bdist.win32\egg\ptcaccount2\accounts.py", line 210, in random_account
  File "build\bdist.win32\egg\ptcaccount2\accounts.py", line 116, in create_account
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PAT
H. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__d
el__ of <selenium.webdriver.chrome.service.Service object at 0x028EF7B0>> ignored`

It looks like the chromedriver isn't working. I tried to reinstall chromedriver, but it only shows me the following:
`Starting ChromeDriver 2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129) on port 9515
Only local connections are allowed.
`

Any help would be greatly appreciated.

**Comment by Kitryn** [comment]
I don't use Windows, but similar error to #11. Also possibly see https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path; also try restarting to reload your PATH variables.

**Comment by Kitryn** [comment]
I just tested it on my Windows VM; it seems that the ChromeDriver executable is not an installer, just the driver itself. Put it in a folder somewhere then:
- Control panel > System > Advanced system settings
- Advanced tab > Environment Variables
- Under the window "System Variables", look for one that says Path
- Click edit
- Type a semicolon (to separate the previous directory and the one you're about to type), then type the folder path to where you put the ChromeDriver executable you downloaded (C:\folder\where\you\put\it)
- Press all the OKs, then restart your command line

Try that and see if it works? If that works, I'll add it to the README.

**Comment by shre0047** [comment]
I'm still getting the same error. 

Once I link the path to chromedriver.exe, do I need to install anything on that aspect or simply run ptc2.exe?

**Comment by Kitryn** [comment]
Link the path to the folder chromedriver is in, then run "ptc2" in the command line (without the .exe) after restarting the command line window. Or maybe try restarting your computer before running ptc2; if you still get an error after, try pasting the whole error log here again?

**Comment by shre0047** [comment]
Here is the log:

C:\Python27\Scripts>ptc2
Creating new account:
Attempting to create user Hs9BThRF0DBqaPl:7BxFM5ac4LUNqwk. Opening browser...
Traceback (most recent call last):
  File "C:\Python27\Scripts\ptc2-script.py", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.2', 'console_scripts', 'ptc2')()
  File "build\bdist.win32\egg\ptcaccount2\console.py", line 47, in entry
  File "build\bdist.win32\egg\ptcaccount2\accounts.py", line 210, in random_account
  File "build\bdist.win32\egg\ptcaccount2\accounts.py", line 116, in create_account
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in **init**
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PAT
H. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__d
el__ of <selenium.webdriver.chrome.service.Service object at 0x0291E7B0>> ignored

C:\Python27\Scripts>

**Comment by Kitryn** [comment]
If you've already linked your PATH correctly, I don't know what else to try. Open your command line and type PATH, what comes out of it?

The chromedriver EXE file doesn't need to be installed or anything, just inside a folder that's listed inside the PATH variable.

**Comment by Kitryn** [comment]
Closing from inactivity.
