### ISSUE TITLE
I get unrecognized arguments

### ISSUE THREAD

**Issue by ewigg** [Kitryn/PTCAccount2#35]
Windows 10, Python 2,7
Using with:

`ptc2 --email=myemail@gmail.com --multiple=2 --tofile`

I get:

`
usage: ptc2-script.py [-h] [-u USERNAME] [-p PASSWORD] [-e EMAIL]
                      [-b BIRTHDAY] [--compact]
ptc2-script.py: error: unrecognized arguments: --multiple=2 --tofile
`

..when trying to use save to file and create more that one account. 

I tried to download it again. Seems I am missing that option?

**Comment by nik-humphries** [comment]
I don't think you're using the most up to date version of ptc2. Try syncing with the latest release.

**Comment by Shadowfish26** [comment]
I don't think you're using the most up to date version of ptc2. Try syncing with the latest release.

**Comment by Shadowfish26** [comment]
I don't think you're using the most up to date version of ptc2. Try syncing with the latest release.

**Comment by Shadowfish26** [comment]
I don't think you're using the most up to date version of ptc2. Try syncing with the latest release.

**Comment by ewigg** [comment]
Got it working by uninstall Python and Git, then reinstalled it. Before that I cloned the latest release, but then I was still missing the options. 

Anyway, its working now :) Solved!
