### ISSUE TITLE
Issue during Creation - cannot find Chrome binary

### ISSUE THREAD

**Issue by l4v4l4mp3** [Kitryn/PTCAccount2#40]
I think its a relly stupid issue but for the moment I am unable to solve it.
So maybe someone can give me a hint. :)

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot fi
nd Chrome binary

**Comment by Kitryn** [comment]
Google Chrome browser has to be installed for this to work, do you have it? That's usually what that error means

**Comment by l4v4l4mp3** [comment]
Yep Chrome is installed (Version 54.0.2839.0)

**Comment by Kitryn** [comment]
What operating system? Is it installed in the default location? On OSX it is the applications folder, on Windows it should be the program files folder.

Are you running a dev version of chrome? The stable version should be v52, the dev branch should be the v54 if I remember correctly from a recent issue

**Comment by l4v4l4mp3** [comment]
Windows 7 
Yep default location ("C:\Users*USER*\AppData\Local\Google\Chrome SxS\Application\chrome.exe")
Yep should be dev version. Might this be the culprit?

**Comment by Kitryn** [comment]
The dev version throws a different error from what you pasted (see #39). I'm not familiar with Windows, but could you double check with https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver to see if that's the correct location?

**Comment by l4v4l4mp3** [comment]
The "Chrome SxS" is diffrent from the given in your link. Maybe this is related to canary version of chrome

**Comment by Kitryn** [comment]
I just noticed the link may also be outdated. Maybe try installing the stable branch of Chome and see where that installs to?

**Comment by l4v4l4mp3** [comment]
Working thx :)

**Comment by Kitryn** [comment]
Curious, did you have to install the stable binary or did it work with the dev branch?

**Comment by l4v4l4mp3** [comment]
Stable version -> created teh necessary folder
