### ISSUE TITLE
Activate acount

### ISSUE THREAD

**Issue by XiAn0x** [Kitryn/PTCAccount2#41]
Just one minor question.
Do you still need to activate all the accounts once you created them, or is this done through the script as well?
Because i created 3 accounts just now with the use of my emails address, but only got one activation mail.

**Comment by Kitryn** [comment]
Nope, the script doesn't do activation. You should have received multiple emails. What parameters are you using, and what email provider? I'm not sure which providers the --email-tag option works with other than gmail

**Comment by XiAn0x** [comment]
It seems that Pokemon is somewhat slow. I eventually received all mails but it just took quite some time.
I used Hotmail.com which works fine on my end, just so you know.

**Comment by Kitryn** [comment]
Alright, thanks! Good to know hotmail also allows the `+<tag>` format.
