### ISSUE TITLE
Confirming Accounts

### ISSUE THREAD

**Issue by brianhrowe** [Kitryn/PTCAccount2#7]
I'm going to test this out after work. I wish Github had an area for just questions/discussion so I didn't have to submit an issue.

But I was wondering if creating multiple accounts with the same email worked so that you can then confirm the account and not have it expire after a few days?

**Comment by Kitryn** [comment]
No, PTC will throw an error saying the email is in use. What you can do however, if you're using gmail, is add a "+" and some text behind your mail. Say your email is foo@gmail.com, you can do...

```
foo+abc@gmail.com
foo+def@gmail.com
foo+asldjalkjsaf@gmail.com
foo+123@gmail.com
```

All these will route email to your original email at foo@gmail.com, but PTC will treat them as separate emails. That's what I've been doing, and seems to be working fine.

**Comment by brianhrowe** [comment]
Thanks. I didn't realize there was a question label

**Comment by brianhrowe** [comment]
@Kitryn I'm trying to get this set up in Windows 10 subsystem for linux which is essentially just Ubuntu.

All of the dependencies seem to have installed fine. But it just hangs when trying to open a browser. Any ideas?

> Creating new account:
> Attempting to create user user:pass. Opening browser...

**Comment by Kitryn** [comment]
I've no experience with Ubuntu unfortunately; is Chrome (the browser) installed? ChromeDriver allows selenium to control chrome but you still need the actual browser installed
