### ISSUE TITLE
issue not resolved in osx 10.11.6

### ISSUE THREAD

**Issue by kuekerino** [Kitryn/PTCAccount2#8]
I am having the same issue as stated in your troubleshoot. Even after editing, uninstalling and reinstalling chromedriver it gives me the same error. 

chromedriver --version
ChromeDriver 2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0)

**Comment by diveflo** [comment]
Might be a error with chromedriver/webdriver itself. I've tried using an older version of chromedriver (2.6), which at least opened. It crashed while trying to enter the birthday, though

**Comment by Kitryn** [comment]
What's the error that it's giving you? I'm on the same OSX version and had no problems doing pip install from github; do you have Chrome itself installed?

**Comment by kuekerino** [comment]
Now I feel stupid. I thought I had it installed yesterday but after double checking chrome was missing...
Thanks
